// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbADQ3xLKIKHmQkTK1EzFCuH-YfrS4k4',
    appId: '1:1071802371727:web:50419c3887583bd010eafa',
    messagingSenderId: '1071802371727',
    projectId: 'minlchat',
    authDomain: 'minlchat.firebaseapp.com',
    storageBucket: 'minlchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd5UyJEsGy1PnWHq7ac4QdZEpjAsedkCI',
    appId: '1:1071802371727:android:06359a1e8e545e3b10eafa',
    messagingSenderId: '1071802371727',
    projectId: 'minlchat',
    storageBucket: 'minlchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwJo_0pITzDicdoul0UerRVCZhMA7_bY',
    appId: '1:1071802371727:ios:7dfe5d60854aa38d10eafa',
    messagingSenderId: '1071802371727',
    projectId: 'minlchat',
    storageBucket: 'minlchat.appspot.com',
    iosClientId: '1071802371727-2kfkmnndvqa5q99hjdc0kd1ijfrnjm2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
